apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding
  labels:
    app: onboarding
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onboarding
  template:
    metadata:
      labels:
        app: onboarding
    spec:
      containers:
        - name: onboarding
          image: vijkum/node-deployment:node
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
