apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-deployment
  template:
    metadata:
      name: node-deployment
      labels:
        app: node-deployment
    spec:
      containers: 
      - name: node-deployment
        image: vijkum/onboarding:node
        env:
        - name: DB_CONNECTION
          value: "mongodb+srv://mdbadmin:Incorrect@cluster0-el86i.azure.mongodb.net/Onboarding?retryWrites=true&w=majority"
        ports:
        - containerPort: 5000
