apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding
spec:
  selector:
    matchLabels:
      app: onboarding
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: onboarding
        tier: backend
        track: stable
    spec:
      containers:
        - name: onboarding
          image: "vijkum/onboarding:node"
          env:
            - name: DB_CONNECTION
              value: "mongodb+srv://mdbadmin:Incorrect@cluster0-el86i.azure.mongodb.net/Onboarding?retryWrites=true&w=majority"
          ports:
            - name: http
              containerPort: 80
