apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding
  labels:
    app: onboarding
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onboarding
  template:
    metadata:
      labels:
        app: onboarding
    spec:
      containers:
        - name: onboarding
          image: vijkum/onboarding:node
          imagePullPolicy: Always
          env:
            - name: DB_MB_CONN
              value: "mongodb+srv://mdbadmin:Incorrect@cluster0-el86i.azure.mongodb.net/Onboarding?retryWrites=true&w=majority"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
