apiVersion: v1
kind: Service
metadata:
  name: node-deployment
  labels:
    app: node-deployment
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: node-deployment
