apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-service    
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: node-pod
