apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-service    
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: node-pod
